name: Manual build workflow
env:
  DOCKER_IMAGE: ijo42/glauncher

on:
  workflow_dispatch:
    inputs:
      launcher_ref:
        description: 'Git ref on GravitLauncher repo'
        required: false
        default: 'master'
      runtime_ref:
        description: 'Git ref on Runtime repo'
        required: false
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DOCKER
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          tags: "${{ env.DOCKER_IMAGE }}:${{ github.event.inputs.launcher_ref }}"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            "LAUNCHER_VERSION=${{ github.event.inputs.launcher_ref }}"
            "RUNTIME_VERSION=${{ github.event.inputs.runtime_ref }}"
