name: Manual build workflow
env:
  DOCKER_IMAGE: ijo42/glauncher

on:
  workflow_dispatch:
    inputs:
      launcher_ref:
        description: 'Git ref on GravitLauncher repo'
        required: false
        default: 'master'
      runtime_ref:
        description: 'Git ref on Runtime repo'
        required: false
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DOCKER
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push amd64
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          tags: "${{ env.DOCKER_IMAGE }}:${{ github.event.inputs.launcher_ref }}"
          push: true
          platforms: linux/amd64
          build-args: |
            "LAUNCHER_VERSION=${{ github.event.inputs.launcher_ref }}"
            "RUNTIME_VERSION=${{ github.event.inputs.runtime_ref }}"
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max

      - name: Build and push arm64
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.aarch64
          tags: "${{ env.DOCKER_IMAGE }}:${{ github.event.inputs.launcher_ref }}-arm64"
          push: true
          platforms: linux/arm64
          build-args: |
            "LAUNCHER_VERSION=${{ github.event.inputs.launcher_ref }}"
            "RUNTIME_VERSION=${{ github.event.inputs.runtime_ref }}"
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache-arm64
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache-arm64,mode=max

