#!/usr/bin/with-contenv bash

for f in 'libraries' 'launcher-libraries' 'launcher-libraries-compile' 'runtime' 'launcher-modules' 'LaunchServer.jar' ; do \
    if [ ! -e /app/launchserver/${f} ]; then
        printf "\n**** missing %s. copying defaults ****\n" "${f}"
        cp -Rfv \
            /defaults/${f} \
            /app/launchserver/
    fi
done
    
chown -R \
  abc:abc \
    /app/launchserver

echo "**** libs checked ****"
